"""empty message

Revision ID: 5719af1b920a
Revises: 8acf52923d09
Create Date: 2025-05-20 10:08:53.603253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5719af1b920a'
down_revision: Union[str, None] = '8acf52923d09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_provider', sa.Enum('Local', 'Google', name='authprovider'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'auth_provider')
    # ### end Alembic commands ###
