"""empty message

Revision ID: 9c4bd5e54b38
Revises: 5719af1b920a
Create Date: 2025-05-21 09:12:13.066274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c4bd5e54b38'
down_revision: Union[str, None] = '5719af1b920a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth_provider',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'auth_provider',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)
    # ### end Alembic commands ###
